[READY] - enable ntpd on core machines
socallinuxexpo/scale-network pull request #665
Opened 2024-01-30 08:26 UTC by sarcasticadmin

## Description of PR

Related to: #592

Getting ntpd enabled and running on the core machines

## Previous Behavior
- ntpd was not running on the core machines

## New Behavior
- ntpd running on core and restricted to scale ipv4 and ipv6 ranges

## Tests
- Running vm locally confirms that is working as expected

2024-02-01 17:05 UTC, owendelong commented
Utterly unnecessary in our environment. For what we are doing, NTP is more than sufficient.Geeking out with PTP might be fun in another context, but here it would just be a distraction. OwenOn Feb 1, 2024, at 06:45, Lee Hughes ***@***.***> wrote:﻿
I've always want to try out ptp. Might be fun.
https://linuxptp.sourceforge.net/

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because your review was requested.Message ID: ***@***.***>

2024-02-02 22:10 UTC, owendelong commented on nix/machines/core/common.nix
That should probably be restrict 2001:470:f026::/48 rather than /64. If we limit to /64, we will block all of the other show subnets.

2024-02-02 22:10 UTC, owendelong requested changes
See note on common.nix

2024-02-02 22:23 UTC, sarcasticadmin commented on nix/machines/core/common.nix
Good catch @owendelong, PR has now been updated

2024-02-06 07:50 UTC, owendelong approved these changes
Thanks for getting this done, Rob.

2024-02-06 07:50 UTC, merged