[REVIEW] - init devServer
socallinuxexpo/scale-network pull request #666
Opened 2024-01-30 08:49 UTC by sarcasticadmin

## Description of PR
Relates to: #660

init the configuration of the `devServer` thats being hosted in northern california

## Previous Behavior
- No dev server :/

## New Behavior
- dev server for all kinds of fun

## Tests
- dev server booted and can `nixos-rebuild switch`

2024-02-01 06:31 UTC, owendelong requested changes
Other than as mentioned above, looks good to me.

2024-02-01 06:31 UTC, owendelong commented on nix/machines/devServer/default.nix
Given that this is the hypervisor and KEA runs as a VM under the hypervisor, it might be best to use a static address for eno1 on this host.

IT appears to me that the tcpdump and mtr packages are not listed, is this an oversight or did I miss something?
Key tools that really should work on all of our hosts include:

- mtr
- tcpdump
- dig
- host
- arp
- ip (iproute2 package usually)
- netstat
- fuser
- lsof
- ssh (client)
- ssh (server) in most if not all cases
- Probably others I am forgetting at the moment, but those are the ones that have hit me hardest on nix systems so far.

2024-02-01 07:24 UTC, sarcasticadmin commented on nix/machines/devServer/default.nix
This PR was originally reflecting the current state of whats been applied to the machine.

> Given that this is the hypervisor and KEA runs as a VM under the hypervisor, it might be best to use a static address for eno1 on this host.

Sure what address would you like to use?

> IT appears to me that the tcpdump and mtr packages are not listed, is this an oversight or did I miss something?
Key tools that really should work on all of our hosts include:

We can add all the packages we want, this is a good list to start. Ill add the additional configuration to this PR for these packages. Packages like ssh-server are already taken care of when enabling the ssh server.

2024-02-01 08:57 UTC, owendelong commented on nix/machines/devServer/default.nix
Awesome. I think the same addresses we previously assigned to the BHyve hypervisors should be good, right?

2024-02-01 17:26 UTC, sarcasticadmin commented on nix/machines/devServer/default.nix
Cleared up the confusion in a sidebar conversation: we'll be leaving `eno1` as dhcp since this is only for the dev Server and not for the hypervisors. That will be in a follow up PR.

2024-02-02 22:07 UTC, owendelong commented on nix/machines/devServer/default.nix
So should I approve and merge this as is or wait for you to mark it ready and re-review?

2024-02-02 23:37 UTC, sarcasticadmin commented on nix/machines/devServer/default.nix
just pushed up the common packages you mentioned, so this is ready for another review

2024-02-06 07:48 UTC, owendelong approved these changes
Looks good to me.

2024-02-06 07:48 UTC, merged