Adds test for switch config types
socallinuxexpo/scale-network pull request #784
Opened 2024-10-01 04:15 UTC by cjmakes

## Description of PR

- Formats switch-config/type so that each config is a single line
- Adds a datasources test for switchconfig types

## Previous Behavior

There was no automation to enforce consistency across switch config types.

## Tests

This pr adds tests. I would appreciate feed back on how to make sure I didn't break any automation that parses the switch configs and relies on using \ to split a config across lines.

closes #676

2024-10-02 05:18 UTC, sarcasticadmin approved these changes
thanks for push this up @cjmakes ! Ill review it more in depth when I have some time later this week, but lets approve it so we can see how CI runs

also tagging @owendelong since this changes the formatting of the switchtypes files slightly

2024-10-09 21:43 UTC, sarcasticadmin reviewed
@cjmakes this looks really good! Left my comments inline so let me know what you think

2024-10-09 21:43 UTC, sarcasticadmin commented on facts/test_datasources.py
> +            "count": "1+",
I think the count here should be `4+` since it looks like we have a mix of `4-6` columns for the config types

2024-10-09 21:43 UTC, sarcasticadmin commented on facts/test_datasources.py
> +                ds.isvalidport,
having `isvalidport` and `isvalidlink` is definitely a great start to testing these switch config types, nice work!

2024-10-09 21:43 UTC, sarcasticadmin commented on switch-configuration/config/types/Booth
> +TRUNK	ge-0/0/0	exSCALE-SLOW,exSCALE-FAST,exSpeaker,exInfra,exAVLAN, exSigns,exVmVendor,vendor_backbone			-	Uplink
Id prefer it we update `test_datafile` to support the `\` for multiline entries. Would you mind seeing how feasible that approach would be?

2024-10-09 21:43 UTC, sarcasticadmin commented
Thanks for fixing the linting errors that came up in CI as well 👍

2024-11-28 19:19 UTC, kylerisse requested changes
still awaiting multi-line support. i say we just close this for now.

2024-12-02 00:19 UTC, sarcasticadmin commented
@cjmakes were going to close this for now since it seems like there are a few limitations with how parse these switch-configuration files after I touched based with @kylerisse 

We can revisit after we have a better plan for approaching the processing of the multiline switch configs and types.

2024-12-02 00:19 UTC, closed without merging